### ISSUE TITLE
ci: addition of automatic deployment

### ISSUE THREAD

**Issue by Skaty** [NUSComputingDev/noticeboard.nuscomputing.com#11]
At the time of writing, there is no automatic deployment of the updated HTML
to noticeboard.nuscomputing.com.

One suggested way to resolve this is to use a CI server.

**Comment by jia1** [comment]
Github pages?

**Comment by Skaty** [comment]
Hmm, depends.

I believe that it would be better if the site is still hosted on our servers. That way, it can be accessed through the intranet.

**Comment by Skaty** [comment]
Closed as current implementation uses GH Pages.
